name: Publish Logger Package
  
on: 
  pull_request:
    branches: [main]

  push:
    branches: [main]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps: 
      - name : Checkout Code
        uses: actions/checkout@v4

      - name : Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install

      - name: Build Package
        run: bun run build

      - name: Publish to NPM
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: bun publish --access public
        env: 
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}